---
title: "Models"
author: "Americo"
date: "21 aprile 2016"
output: html_document
---


```{r partizione training e test}
set.seed(19121984)

training_set <- bank0 %>%
        add_rownames() %>%
        sample_frac(0.8, replace = FALSE)

test_set <- bank0 %>%
        add_rownames() %>%
        sample_frac(1, replace = FALSE) %>%
        anti_join(training_set, by = "rowname")
#check ok, sono diversi
```

```{r k fold in training}
set.seed(123)
flds <- createFolds(training_set$y, k = 10, list = TRUE, returnTrain = FALSE)
bank_fold1 <- training_set[flds[[1]], ]
bank_fold2 <- training_set[flds[[2]], ]
bank_fold3 <- training_set[flds[[3]], ]
bank_fold4 <- training_set[flds[[4]], ]
bank_fold5 <- training_set[flds[[5]], ]
bank_fold6 <- training_set[flds[[6]], ]
bank_fold7 <- training_set[flds[[7]], ]
bank_fold8 <- training_set[flds[[8]], ]
bank_fold9 <- training_set[flds[[9]], ]
bank_fold10 <- training_set[flds[[10]], ]
```


#Validation set apprach

Creo training_vsa, validation_vsa, test_vsa. Con questa partizione posso attuare il validation approach e modellare e diagnosticare si training, selezionare su validation e testare su test.


```{r partizione training validation e test}
set.seed(456)
training_set_vsa <- bank0 %>%
        add_rownames() %>%
        sample_frac(0.6, replace = FALSE)
nrow(training_set_vsa)

test_and_val_set1 <- bank0 %>%
        add_rownames() %>%
        sample_frac(1, replace = FALSE) %>%
        anti_join(training_set_vsa, by = "rowname")
nrow(test_and_val_set1)
#check ok, sono diversi

test_set_vsa <- test_and_val_set1 %>%
        sample_frac(0.5, replace = FALSE)
nrow(test_set_vsa)

validation_set_vsa <- test_and_val_set1 %>%
        sample_frac(1, replace = FALSE) %>%
        anti_join(test_set_vsa, by = "rowname")
nrow(validation_set_vsa)

validation_set_vsa[validation_set_vsa$rowname == test_set_vsa$rowname,] #check ok, tutte righe diverse
```